# yaml-language-server: $schema: https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
---
name: "FOLIO User Import Docker Build"

on:
  workflow_dispatch:
    inputs:
      image-version:
        description: "Version for image tag"
        type: "string"
        required: true

env:
  REGISTRY: ghcr.io
  NAMESPACE: Five-Colleges-Incorporated
  IMAGE_NAME: folio-user-import
  IMAGE_TITLE: Folio User Import
  IMAGE_DESCRIPTION: 5C Build of folio_data_import for importing Users

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      artifact-metadata: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract package version
        id: package_version
        run: |
          echo version="$(grep 'folio-data-import==' $IMAGE_NAME/requirements.lock | awk -F'==' '{ print $2 }')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Validate image version
        run: |
          PKG_VERSION="${{ steps.package_version.outputs.version }}"
          INPUT_VERSION="${{ inputs.image-version }}"

          if [[ "$INPUT_VERSION" != "$PKG_VERSION"-* ]]; then
            echo "Image version ($INPUT_VERSION) must start with package version ($PKG_VERSION)"
            exit 1
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='America/New_York'}}
            type=raw,value=${{ steps.package_version.outputs.version }}
            type=semver,pattern={{version}},value=${{ inputs.image-version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.image-version }}
            type=semver,pattern={{major}},value=${{ inputs.image-version }}
          labels: |
            org.opencontainers.image.vendor=Five College Incorporated
            org.opencontainers.image.authors=Katherine Bargar <kbargar@fivecolleges.edu>
            org.opencontainers.image.title=${{ env.IMAGE_TITLE }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.url=${{ github.repository }}/${{ env.IMAGE_NAME }}
            org.opencontainers.image.source=${{ github.repository }}/${{ env.IMAGE_NAME }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ inputs.image-version }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.IMAGE_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
