# yaml-language-server: $schema: https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
---
name: "Setae API Docker Build"

on:
  workflow_dispatch:
    inputs:
      image-version:
        description: "Version of image tag"
        type: "string"
        required: true

env:
  REGISTRY: ghcr.io
  NAMESPACE: Five-Colleges-Incorporated
  IMAGE_NAME: setae-api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='America/New_York'}}
            type=semver,pattern={{version}},value=${{ inputs.image-version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.image-version }}
            type=semver,pattern={{major}},value=${{ inputs.image-version }}
          labels: |
            org.opencontainers.image.description=5C Build of API middleware to support LTS workflows in FOLIO
            org.opencontainers.image.source=https://github.com/Five-Colleges-Incorporated/setae-api
            org.opencontainers.image.title=${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=https://github.com/Five-Colleges-Incorporated/library-docker-images/setae-api

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./setae-api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
